/* libicq2000/version.h.  Generated by configure.  */
#ifndef _LIBICQ2000_CONFIG_H_
#define _LIBICQ2000_CONFIG_H_

/* version numbers */
#define LIBICQ2000_MAJOR_VERSION 0
#define LIBICQ2000_MINOR_VERSION 3
#define LIBICQ2000_MICRO_VERSION 2
#define LIBICQ2000_VERSION "0.3.2"

extern unsigned int libicq2000_major_version;
extern unsigned int libicq2000_minor_version;
extern unsigned int libicq2000_micro_version;
extern const char *libicq2000_version;

#endif
