#!/bin/sh
CC=gcc
CXX=g++
COMMON_CFLAGS= -g -Wall -I. -I../jabberd -I/usr/include -DWPJABBER -I/usr/include -fPIC
COMMON_LIBS= -ldl -lpthread
JHOME=/usr/local
PREFIX=/usr/local
CONFIG_FILE=jabber.xml
OUT_FILE=jabberd-jit
JABBERD_EXPORTS_LIB=
JABBERD_CYGWIN_LIB=
JIT_MODULE=jit.so
XDB_MODULE=xdb_file.so
